LeadManagementSystem/Controllers/AssigneeController.cs
using LeadManagementSystem.MODEL;
using LeadManagementSystem.MyServices;
using LeadManagementSystem.Service;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeadManagementSystem.Controllers
{
    [SessionOut]
    public class AssigneeController : Controller
    {
        ResponseStatusModel rm = new ResponseStatusModel();
        public ActionResult Index()
        {
            if (Session["AuthToken"] != null)
            {
                return View();
            }
            else
            {
                rm.msg = "Expired";
                rm.n = 5;
                return RedirectToAction("LogInForm", "LogIn");
            }
        }
        public ActionResult AssigneeTablePartial()
        {
            if (Session["AuthToken"] != null)
            {
                AssigneeModel lm = new AssigneeModel();
                AssigneeDetails cd = new AssigneeDetails();
                var result = JsonConvert.DeserializeObject<AssigneeModel>(LMSTransaction.get("GetAssigneeList", Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                lm.AssigneeList = result.AssigneeList;
                return PartialView("AssigneeTablePartial", lm);
            }
            else
            {
                rm.msg = "Expired";
                rm.n = 5;
                return RedirectToAction("LogInForm", "LogIn");
            }
        }
        public ActionResult AddNewAssignee(AssigneeDetails ld)
        {
            try
            {
                if (Session["AuthToken"] != null)
                {
                    ld.CreatedBy = Convert.ToString(Session["Admin_ID"]);
                    var result = JsonConvert.DeserializeObject<ResponseStatusModel>(LMSTransaction.post("AddNewAssignee", ld, Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                    rm = result;
                }
                else
                {
                    rm.n = 5;
                    rm.msg = "Session Expired";
                }
            }
            catch (Exception ex)
            {
                rm.RStatus = "Error";
                rm.msg = "Some error occured while processing your request, Please try again later";
                rm.n = 0;
            }
            return Json(rm, JsonRequestBehavior.AllowGet);
        }
        public ActionResult DeleteAssignee(string id)
        {
            try
            {
                if (Session["AuthToken"] != null)
                {
                    var result = JsonConvert.DeserializeObject<ResponseStatusModel>(LMSTransaction.get("RemoveAssignee?id=" + id, Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                    rm = result;
                }
                else
                {
                    rm.n = 5;
                    rm.msg = "Session Expired";
                }
            }
            catch (Exception ex)
            {
                rm.RStatus = "Error";
                rm.msg = "Some error occured while processing your request, Please try again later";
                rm.n = 0;
            }
            return Json(rm, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ViewAssignToDetails(string id)
        {
            try
            {
                if (Session["AuthToken"] != null)
                {
                    AssigneeDetails ld = new AssigneeDetails();
                    var result = JsonConvert.DeserializeObject<AssigneeDetails>(LMSTransaction.get("ViewAssignToDetails?Assignee_Id=" + id, Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                    ld = result;
                    return Json(ld, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    rm.n = 5;
                    rm.msg = "Session Expired";
                    return Json(rm, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                rm.RStatus = "Error";
                rm.msg = "Some error occured while processing your request, Please try again later";
                rm.n = 0;
            }
            return Json(rm, JsonRequestBehavior.AllowGet);
        }
        public ActionResult UpdateAssignee(AssigneeDetails ad)
        {
            try
            {
                if (Session["AuthToken"] != null)
                {
                    ad.CreatedBy = Convert.ToString(Session["Admin_ID"]);
                    var result = JsonConvert.DeserializeObject<ResponseStatusModel>(LMSTransaction.post("UpdateAssignee", ad, Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                    rm = result;
                }
                else
                {
                    rm.n = 5;
                    rm.msg = "Session Expired";
                }
            }
            catch (Exception ex)
            {
                rm.RStatus = "Error";
                rm.msg = "Some error occured while processing your request, Please try again later";
                rm.n = 0;
            }
            return Json(rm, JsonRequestBehavior.AllowGet);
        }
    }
}

LeadManagementSystem/Views/Assignee/AssigneeTablePartial.cshtml
@model LeadManagementSystem.MODEL.AssigneeModel

@if (Model.AssigneeList.Count < 0 || Model.AssigneeList != null)
{
    <table class="table" id="TableAssignee">
        <thead>
            <tr>
                <th class="text-center">Sr.No</th>
                <th class="text-center">Assignee Name</th>
                <th class="text-center" id="colAction">Action</th>
            </tr>
        </thead>
        <tbody class="text-center">
            @for (int i = 0; i < Model.AssigneeList.Count; i++)
            {
                <tr>
                    <td>@Model.AssigneeList[i].RowNum</td>
                    <td>@Model.AssigneeList[i].Assignee_Name</td>
                    <td style="padding: 3px;">
                        <div class="btn-group">
                            <a data-toggle="tooltip" title="Update" data-placement="left" class="btn btn-sm waves-effect" style="padding-left: 3px; padding-right: 3px; width: 25px; height: 29px;"><i class="fa fa-edit" onclick="EditAssigneeDetails(@Model.AssigneeList[i].Assignee_Id);"></i></a>
                            @if (Session["Admin_ID"].ToString() == "1" || Session["Admin_ID"].ToString() == @Model.AssigneeList[i].CreatedBy)
                            {<a data-toggle="tooltip" title="delete" data-placement="left" class="btn btn-sm waves-effect" style="padding-left: 3px; padding-right: 3px; width: 25px; height: 29px;"><i class="fa fa-trash" onclick="RemoveAssignee(@Model.AssigneeList[i].Assignee_Id);"></i></a>
                            }
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <table class="table" id="TableAssignee">
        <thead>
            <tr>
                <th class="text-center">Sr.No</th>
                <th class="text-center">Assignee Name</th>
                <th class="text-center" id="colAction">Action</th>
            </tr>
        </thead>
        <tbody class="text-center">
            <tr>
                <td class="text-center">No data Found</td>
            </tr>
        </tbody>
    </table>
}

LeadManagementSystem/Views/Assignee/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
<link href="~/ThemeContent/css/EmployeeStyleSheet.css" rel="stylesheet" />
<section class="content-header padding-title">
    <h1>Assignee Details</h1>
</section>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary with-border" id="AssigneeDataDIV">
            <div class="box-header with-border">
                <h3 class="box-title" id="boxTitle">Add Assignee Details</h3>
            </div>
            <div class="box-body">
                <div class="col-md-12 padding-left" id="AssigneeForm">
                    <div class="col-md-4 padding-left">
                        <div class="form-group">
                            <div class="box-body padding-left">
                                <div class="form-group" id="AssigneeNameDIV">
                                    <label>Assignee Name<span class="text-danger">*</span></label>
                                    <input type="text" class="form-control" maxlength="25" id="TxtAssigneeName" placeholder="Enter Assignee Name" autocomplete="off" />
                                    <span class="help-block" id="ErrorForAssigneeName"></span>
                                </div>
                            </div>
                            <div class="box-footer padding-left">
                                <button type="button" class="btn btn-success" id="btnSave" onclick="SaveFormData();" style="margin-right: 10px;width:110px;">Save</button>
                                <button type="button" class="btn btn-danger" id="btnreset" onclick="ResetFormData();" style="width:110px;">Reset</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8" id="AssigneeTable">
                        <div class="box box-primary with-border">
                            <div class="box-body">
                                <div id="AssigneeDetails"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section LocalJs{
    <script>
        $(document).ready(function () {
            debugger;
            refreshDataTable(0)
        });
        function refreshDataTable(pageId) {
            debugger;
            $("#AssigneeDetails").load("@Url.Action("AssigneeTablePartial", "Assignee")", function () {

                var pageToSet = pageId;
                var myDataTable = $('#TableAssignee').DataTable({
                });
                $("#TableAssignee").removeClass('dataTable');
                $(".col-sm-12").addClass('overflow');
                $(".col-sm-12").css('padding-right', '0px');
                if (pageId != 0) {
                    sessionStorage.setItem('pageId', 0);
                }
                myDataTable.page(pageToSet).draw(false);
            });
        }
    </script>
    <script src="~/MyJavascripts/Assignee.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.13.5/jszip.js"></script>
    <script src="https://unpkg.com/bootstrap-multiselect@0.9.13/dist/js/bootstrap-multiselect.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
}