LeadManagementSystem/Controllers/CategoryController.cs
using LeadManagementSystem.MODEL;
using LeadManagementSystem.MyServices;
using LeadManagementSystem.Service;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeadManagementSystem.Controllers
{
    [SessionOut]
    public class CategoryController : Controller
    {
        private  int GetSessionTimeoutFromConfig()
        {
            try
            {
                // Retrieve the session timeout value from httpRuntime in web.config
                var sessionStateSection = System.Web.Configuration.WebConfigurationManager.GetSection("system.web/sessionState") as System.Web.Configuration.SessionStateSection;
                if (sessionStateSection != null)
                {
                    int sessionTimeoutMinutes = (int)sessionStateSection.Timeout.TotalMinutes;
                    return sessionTimeoutMinutes;
                }
                return 30;
            }
            catch (Exception ex)
            {
                // Log or handle any exceptions
                Console.WriteLine($"Error retrieving session timeout: {ex.Message}");
                return 20; // Set your default value here
            }
        }
        ResponseStatusModel rm = new ResponseStatusModel();
        public ActionResult Index()
        {
            if (Session["AuthToken"] != null)
            {
                return View();
            }
            else
            {
                rm.msg = "Expired";
                rm.n = 5;
                return RedirectToAction("LogInForm", "LogIn");
            }
        }
        public ActionResult CategoryTablePartial()
        {
            if (Session["AuthToken"] != null)
            {
                int sessionTimeoutMinutes = GetSessionTimeoutFromConfig();

                // Display the session timeout in the view
                ViewBag.SessionTimeout = sessionTimeoutMinutes;
                LeadCategoryModel lcm = new LeadCategoryModel();
                LeadCategoryDetails cd = new LeadCategoryDetails();
                var result = JsonConvert.DeserializeObject<LeadCategoryModel>(LMSTransaction.get("GetLeadCategoryList", Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                lcm.LeadCategoryList = result.LeadCategoryList;
                return PartialView("CategoryTablePartial", lcm);
            }
            else
            {
                rm.msg = "Expired";
                rm.n = 5;
                return RedirectToAction("LogInForm", "LogIn");
            }
            
        }
        public ActionResult ViewCategoryDetails(string id)
        {
            try
            {
                if (Session["AuthToken"] != null)
                {
                    LeadCategoryDetails ld = new LeadCategoryDetails();
                    var result = JsonConvert.DeserializeObject<LeadCategoryDetails>(LMSTransaction.get("ViewCategoryDetails?Category_Id=" + id, Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                    ld = result;
                    return Json(ld, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    rm.n = 5;
                    rm.msg = "Session Expired";
                    return Json(rm, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                rm.RStatus = "Error";
                rm.msg = "Some error occured while processing your request, Please try again later";
                rm.n = 0;
            }
            return Json(rm, JsonRequestBehavior.AllowGet);

        }
        public ActionResult AddCategory(LeadCategoryDetails ld)
        {
            try
            {
                if (Session["AuthToken"] != null)
                {
                    ld.CreatedBy = Convert.ToString(Session["Admin_ID"]);
                    var result = JsonConvert.DeserializeObject<ResponseStatusModel>(LMSTransaction.post("AddCategory", ld, Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                    rm = result;
                }
                else
                {
                    rm.n = 5;
                    rm.msg = "Session Expired";
                }
            }
            catch (Exception ex)
            {
                rm.RStatus = "Error";
                rm.msg = "Some error occured while processing your request, Please try again later";
                rm.n = 0;
            }
            return Json(rm, JsonRequestBehavior.AllowGet);
        }
        public ActionResult DeleteCategory(string id)
        {
            try
            {
                if (Session["AuthToken"] != null)
                {
                    var result = JsonConvert.DeserializeObject<ResponseStatusModel>(LMSTransaction.get("RemoveCategory?id=" + id, Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                    rm = result;
                }
                else
                {
                    rm.n = 5;
                    rm.msg = "Session Expired";
                }
            }
            catch (Exception ex)
            {
                rm.RStatus = "Error";
                rm.msg = "Some error occured while processing your request, Please try again later";
                rm.n = 0;
            }
            return Json(rm, JsonRequestBehavior.AllowGet);
        }
        public ActionResult UpdateCategory(LeadCategoryDetails cd)
        {
            try
            {
                if (Session["AuthToken"] != null)
                {
                    cd.CreatedBy = Convert.ToString(Session["Admin_ID"]);
                    var result = JsonConvert.DeserializeObject<ResponseStatusModel>(LMSTransaction.post("UpdateCategory", cd, Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                    rm = result;
                }
                else
                {
                    rm.n = 5;
                    rm.msg = "Session Expired";
                }
            }
            catch (Exception ex)
            {
                rm.RStatus = "Error";
                rm.msg = "Some error occured while processing your request, Please try again later";
                rm.n = 0;
            }
            return Json(rm, JsonRequestBehavior.AllowGet);
        }
    }
}

LeadManagementSystem/Controllers/TypeOfLeadController.cs
using LeadManagementSystem.MODEL;
using LeadManagementSystem.MyServices;
using LeadManagementSystem.Service;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LeadManagementSystem.Controllers
{
    [SessionOut]
    public class TypeOfLeadController : Controller
    {
        ResponseStatusModel rm = new ResponseStatusModel();
        public ActionResult Index()
        {
            if (Session["AuthToken"] != null)
            {
                var leadCategoryList = JsonConvert.DeserializeObject<LeadCategoryModel>(LMSTransaction.get("GetLeadCategoryList", Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                List<LeadCategoryDetails> LeadCategoryDetails = leadCategoryList.LeadCategoryList;
                var leadCategoryNames = "";
                foreach (var LeadCategory in LeadCategoryDetails)
                {
                    leadCategoryNames += "<option value='" + LeadCategory.Category_Id + "'>" + LeadCategory.Category_Name + "</option>";
                }
                ViewBag.CategoryModelList = leadCategoryNames;
                return View();
            }
            else
            {
                rm.msg = "Expired";
                rm.n = 5;
                return RedirectToAction("LogInForm", "LogIn");
            }
        }
        public ActionResult TypeOfLeadTablePartial()
        {
            if (Session["AuthToken"] != null)
            {
                SubCategoryModel lm = new SubCategoryModel();
                SubCategoryDetails cd = new SubCategoryDetails();
                var result = JsonConvert.DeserializeObject<SubCategoryModel>(LMSTransaction.get("GetSubCategoryList", Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                lm.SubCategoryList = result.SubCategoryList;
                return PartialView("TypeOfLeadTablePartial", lm);
            }
            else
            {
                rm.msg = "Expired";
                rm.n = 5;
                return RedirectToAction("LogInForm", "LogIn");
            }
        }
        public ActionResult AddSubCategory(SubCategoryDetails ld)
        {
            try
            {
                if (Session["AuthToken"] != null)
                {
                    ld.CreatedBy = Convert.ToString(Session["Admin_ID"]);
                    var result = JsonConvert.DeserializeObject<ResponseStatusModel>(LMSTransaction.post("AddSubCategory", ld, Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                    rm = result;
                }
                else
                {
                    rm.n = 5;
                    rm.msg = "Session Expired";
                }
            }
            catch (Exception ex)
            {
                rm.RStatus = "Error";
                rm.msg = "Some error occured while processing your request, Please try again later";
                rm.n = 0;
            }
            return Json(rm, JsonRequestBehavior.AllowGet);
        }
        public ActionResult DeleteSubCategory(string id)
        {
            try
            {
                if (Session["AuthToken"] != null)
                {
                    var result = JsonConvert.DeserializeObject<ResponseStatusModel>(LMSTransaction.get("RemoveSubCategory?id=" + id, Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                    rm = result;
                }
                else
                {
                    rm.n = 5;
                    rm.msg = "Session Expired";
                }
            }
            catch (Exception ex)
            {
                rm.RStatus = "Error";
                rm.msg = "Some error occured while processing your request, Please try again later";
                rm.n = 0;
            }
            return Json(rm, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ViewSubCategoryDetails(string id)
        {
            try
            {
                if (Session["AuthToken"] != null)
                {
                    SubCategoryDetails ld = new SubCategoryDetails();
                    var result = JsonConvert.DeserializeObject<SubCategoryDetails>(LMSTransaction.get("ViewSubCategoryDetails?SubCategory_ID=" + id, Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                    ld = result;
                    return Json(ld, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    rm.n = 5;
                    rm.msg = "Session Expired";
                    return Json(rm, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                rm.RStatus = "Error";
                rm.msg = "Some error occured while processing your request, Please try again later";
                rm.n = 0;
            }
            return Json(rm, JsonRequestBehavior.AllowGet);
        }
        public ActionResult UpdateSubCategory(SubCategoryDetails ld)
        {
            try
            {
                if (Session["AuthToken"] != null)
                {
                    ld.CreatedBy = Convert.ToString(Session["Admin_ID"]);
                    var result = JsonConvert.DeserializeObject<ResponseStatusModel>(LMSTransaction.post("UpdateSubCategory", ld, Session["AuthToken"].ToString(), Session["Admin_ID"].ToString()).Content);
                    rm = result;
                }
                else
                {
                    rm.n = 5;
                    rm.msg = "Session Expired";
                }
            }
            catch (Exception ex)
            {
                rm.RStatus = "Error";
                rm.msg = "Some error occured while processing your request, Please try again later";
                rm.n = 0;
            }
            return Json(rm, JsonRequestBehavior.AllowGet);
        }
    }
}

LeadManagementSystem/Views/TypeOfLead/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
<style>
    #TxtSubCategoryName {
        width: 80%;
    }
</style>
<link href="~/ThemeContent/css/TypeOfLeadStyleSheet.css" rel="stylesheet" />
<section class="content-header padding-title">
    <h1 id="boxTitle">Sub Category Details</h1>
</section>
<div class="row">
    <div class="col-md-12">
        <div class="box box-primary with-border" id="SubCategoryDataDIV">
            <div class="box-header with-border">
                <div class="tab-header">
                    <div class="tab" onclick="@("window.location.href='" + @Url.Action("Index", "Category") + "'");">Add Category</div>
                    <div class="tab active" onclick="@("window.location.href='" + @Url.Action("Index", "TypeOfLead") + "'");">Add Sub Category</div>
                </div>
            </div>
            <div class="box-body">
                <div class="col-md-12 padding-left" id="SubCategoryForm">
                    <div class="col-md-4 padding-left">
                        <div class="form-group">
                            <div class="box-body padding-left">
                                <div class="form-group" id="CategoryNameDIV">
                                    <label>Category Name<span class="text-danger">*</span></label>
                                    <select id="TxtCategory" class="form-control">
                                        <option selected="" value="">--Select Category--</option>
                                        @Html.Raw(ViewBag.CategoryModelList)
                                    </select>
                                    <span class="help-block" id="ErrorForCategoryName"></span>
                                </div>
                                <div class="form-group" id="SubCategoryNameDIV">
                                    <label>Sub Category Name<span class="text-danger">*</span></label>
                                    <input type="text" maxlength="25" class="form-control" id="TxtSubCategoryName" placeholder="Enter Sub Category Name" autocomplete="off" />
                                    <span class="help-block" id="ErrorForSubCategoryName"></span>
                                </div>
                            </div>
                            <div class="box-footer padding-left">
                                <button type="button" class="btn btn-success" id="btnSave" onclick="SaveFormData();" style="margin-right: 10px;width:110px;">Save</button>
                                <button type="button" class="btn btn-danger" id="btnreset" onclick="ResetFormData();" style="width:110px;">Reset</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-8" id="SubCategoryTable">
                        <div class="box box-primary with-border">
                            <div class="box-body">
                                <div id="SubCategoryDetails"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section LocalJs{
    <script>
        $(document).ready(function () {
            debugger;
            refreshDataTable(0)
        });
        function refreshDataTable(pageId) {
            debugger;
            $("#SubCategoryDetails").load("@Url.Action("TypeOfLeadTablePartial", "TypeOfLead")", function () {
                var pageToSet = pageId;
                var myDataTable = $('#TableSubCategory').DataTable({
                });
                $("#TableSubCategory").removeClass('dataTable');
                $(".col-sm-12").addClass('overflow');
                $(".col-sm-12").css('padding-right', '0px');
                if (pageId != 0) {
                    sessionStorage.setItem('pageId', 0);
                }
                myDataTable.page(pageToSet).draw(false);
            });
        }
    </script>
    <script src="~/MyJavascripts/TypeOfLead.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.13.5/jszip.js"></script>
    <script src="https://unpkg.com/bootstrap-multiselect@0.9.13/dist/js/bootstrap-multiselect.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.0/js/bootstrap-datepicker.min.js"></script>
}

LeadManagementSystem/Views/TypeOfLead/TypeOfLeadTablePartial.cshtml
@model LeadManagementSystem.MODEL.SubCategoryModel

@if (Model.SubCategoryList.Count > 0 || Model.SubCategoryList != null)
{

    <table class="table" id="TableSubCategory">
        <thead>
            <tr>
                <th class="text-center">Sr.No</th>
                <th class="text-center">Category Name</th>
                <th class="text-center">Sub Category Name</th>
                <th class="text-center" id="colAction">Action</th>
            </tr>
        </thead>
        <tbody class="text-center">
            @for (int i = 0; i < Model.SubCategoryList.Count; i++)
            {
                <tr>
                    <td>@Model.SubCategoryList[i].RowNum</td>
                    <td>@Model.SubCategoryList[i].Category_Name</td>
                    <td>@Model.SubCategoryList[i].SubCategory</td>

                    <td style="padding: 3px;">
                        <div class="btn-group">

                            <a data-toggle="tooltip" title="Update" data-placement="left" class="btn btn-sm waves-effect" style="padding-left: 3px; padding-right: 3px; width: 25px; height: 29px;"><i class="fa fa-edit" onclick="EditSubCategory(@Model.SubCategoryList[i].SubCategory_ID);"></i></a>
                            @if (Session["Admin_ID"].ToString() == "1" || Session["Admin_ID"].ToString() == @Model.SubCategoryList[i].CreatedBy)
                            {<a data-toggle="tooltip" title="delete" data-placement="left" class="btn btn-sm waves-effect" style="padding-left: 3px; padding-right: 3px; width: 25px; height: 29px;"><i class="fa fa-trash" onclick="RemoveSubCategory(@Model.SubCategoryList[i].SubCategory_ID);"></i></a>
                            }
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <table class="table" id="TableSubCategory">
        <thead>
            <tr>
                <th class="text-center">Sr.No</th>
                <th class="text-center">Category Name</th>
                <th class="text-center">Sub Category Name</th>
                <th class="text-center" id="colAction">Action</th>
            </tr>
        </thead>
        <tbody class="text-center">
            <tr>
                <td class="text-center">No data Found</td>
            </tr>
        </tbody>
    </table>
}